---
openshift_master_config_dir: "{{ openshift.common.config_base }}/master"
es_node_quorum: "{{openshift_logging_es_cluster_size/2 + 1}}"
es_recover_after_nodes: "{{openshift_logging_es_cluster_size - 1}}"
es_recover_expected_nodes: "{{openshift_logging_es_cluster_size}}"
es_ops_node_quorum: "{{openshift_logging_es_ops_cluster_size/2 + 1}}"
es_ops_recover_after_nodes: "{{openshift_logging_es_ops_cluster_size - 1}}"
es_ops_recover_expected_nodes: "{{openshift_logging_es_ops_cluster_size}}"
